/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * register
         * @description สมัครสมาชิก
         */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @example application/json */
                    "Content-Type"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /** @example  */
                    "application/json": {
                        first_name: string;
                        last_name: string;
                        /** Format: date */
                        birthday: string;
                        allergy?: string | null;
                        /** Format: email */
                        email: string;
                        phone: string;
                        /**
                         * @default active
                         * @example active
                         */
                        status?: string | null;
                        citizen_id: string;
                        password: string;
                    };
                };
            };
            responses: {
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                /** @description ID */
                                id: number;
                                /** Format: email */
                                email: string;
                                name: string;
                            };
                        };
                    };
                };
                409: components["responses"]["409 Conflict"];
                500: components["responses"]["500 Internal Server Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** login */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: {
                                account_id: number;
                                username: string;
                                role: string;
                                token: string;
                            };
                        };
                    };
                };
                400: components["responses"]["400 Bad Request"];
                500: components["responses"]["500 Internal Server Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/patients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** patients */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description List of patients */
                            data: {
                                /** @description Unique identifier of patient */
                                id: number;
                                /** @description Full name of patient */
                                name: string;
                                /**
                                 * Format: email
                                 * @description Email address of patient
                                 */
                                email: string;
                            }[];
                        };
                    };
                };
                401: components["responses"]["401 Unauthorized"];
                403: components["responses"]["403 Forbidden"];
                500: components["responses"]["500 Internal Server Error"];
            };
        };
        put?: never;
        /** patient */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @example application/json */
                    "Content-Type"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        first_name: string;
                        last_name: string;
                        /** Format: date */
                        birthday: string;
                        allergy?: string | null;
                        /** Format: email */
                        email: string;
                        phone: string;
                        /**
                         * @default active
                         * @example active
                         */
                        status?: string | null;
                        citizen_id: string;
                    };
                };
            };
            responses: {
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                name: string;
                                /** Format: email */
                                email: string;
                                id: number;
                                /** Format: date */
                                birthday: string;
                                phone: string;
                                allergy?: string | null;
                            };
                        };
                    };
                };
                400: components["responses"]["400 Bad Request"];
                401: components["responses"]["401 Unauthorized"];
                403: components["responses"]["403 Forbidden"];
                409: components["responses"]["409 Conflict"];
                500: components["responses"]["500 Internal Server Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/patients/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** patient */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["patient"];
                        };
                    };
                };
                401: components["responses"]["401 Unauthorized"];
                403: components["responses"]["403 Forbidden"];
                404: components["responses"]["404 Not Found"];
                500: components["responses"]["500 Internal Server Error"];
            };
        };
        /** patient */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        first_name: string;
                        last_name: string;
                        /** Format: date */
                        birthday: string;
                        allergy?: string | null;
                        /** Format: email */
                        email: string;
                        phone: string;
                        /**
                         * @default active
                         * @example active
                         */
                        status?: string | null;
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                id: number;
                                name: string;
                                /** Format: email */
                                email: string;
                                /** Format: date */
                                birthday: string;
                                phone: string;
                                allergy?: string | null;
                            };
                        };
                    };
                };
                400: components["responses"]["400 Bad Request"];
                401: components["responses"]["401 Unauthorized"];
                403: components["responses"]["403 Forbidden"];
                404: components["responses"]["404 Not Found"];
                409: components["responses"]["409 Conflict"];
                422: components["responses"]["422 Unprocessable Entity"];
                500: components["responses"]["500 Internal Server Error"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/appointments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** appointments */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                appointment_id: number;
                                patient: {
                                    /** @description ID */
                                    id: number;
                                    /** @description name */
                                    name: string;
                                };
                                staff: {
                                    id: number;
                                    /** @description name */
                                    name: string;
                                };
                                appointment_date: string;
                                appointment_time: string;
                                type: string;
                                /** @enum {string} */
                                status: "scheduled" | "completed" | "cancelled" | "request_cancel";
                                medical_record_id: number | null;
                                inspection_record_id: number | null;
                            }[];
                        };
                    };
                };
                400: components["responses"]["400 Bad Request"];
                401: components["responses"]["401 Unauthorized"];
                403: components["responses"]["403 Forbidden"];
                500: components["responses"]["500 Internal Server Error"];
            };
        };
        put?: never;
        /** appointments */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @example application/json */
                    "Content-Type"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "patient_id": 35,
                     *       "appointment_date": "2026-03-09T07:16:56.392Z",
                     *       "appointment_time": "2026-03-09T07:16:56.392Z",
                     *       "type": "culpa do aliquip est"
                     *     }
                     */
                    "application/json": {
                        patient_id: number;
                        /** Format: date-time */
                        appointment_date: string;
                        /** Format: time */
                        appointment_time: string;
                        type: string;
                    };
                };
            };
            responses: {
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                appointment_id: number;
                                patient: {
                                    /** @description ID */
                                    id: number;
                                    /** @description name */
                                    name: string;
                                };
                                staff: {
                                    id: number;
                                    /** @description name */
                                    name: string;
                                };
                                appointment_date: string;
                                appointment_time: string;
                                type: string;
                                /** @enum {string} */
                                status: "scheduled" | "completed" | "cancelled" | "request_cancel";
                                medical_record?: {
                                    /** @description ID */
                                    id: number;
                                    date: string;
                                    history: string;
                                    status: string;
                                    detail: {
                                        id: number;
                                        type_id: number;
                                        diagnosis: string;
                                    }[];
                                } | null;
                                inspection_record?: {
                                    /** @description ID */
                                    id: number;
                                    /** Format: date */
                                    date: string;
                                    history: string;
                                    status: string;
                                } | null;
                            };
                        };
                    };
                };
                400: components["responses"]["400 Bad Request"];
                401: components["responses"]["401 Unauthorized"];
                403: components["responses"]["403 Forbidden"];
                409: components["responses"]["409 Conflict"];
                422: components["responses"]["422 Unprocessable Entity"];
                500: components["responses"]["500 Internal Server Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/appointments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** appointments */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example 2 */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                appointment_id: number;
                                patient: {
                                    /** @description ID */
                                    id: number;
                                    /** @description name */
                                    name: string;
                                };
                                staff: {
                                    id: number;
                                    /** @description name */
                                    name: string;
                                };
                                appointment_date: string;
                                appointment_time: string;
                                type: string;
                                /** @enum {string} */
                                status: "scheduled" | "completed" | "cancelled" | "request_cancel";
                                medical_record?: {
                                    /** @description ID */
                                    id: number;
                                    date: string;
                                    history: string;
                                    status: string;
                                    detail: {
                                        id: number;
                                        type_id: number;
                                        diagnosis: string;
                                    }[];
                                } | null;
                                inspection_record?: {
                                    /** @description ID */
                                    id: number;
                                    /** Format: date */
                                    date: string;
                                    history: string;
                                    status: string;
                                } | null;
                            };
                        };
                    };
                };
                400: components["responses"]["400 Bad Request"];
                401: components["responses"]["401 Unauthorized"];
                403: components["responses"]["403 Forbidden"];
                500: components["responses"]["500 Internal Server Error"];
            };
        };
        /** appointments */
        put: {
            parameters: {
                query?: never;
                header?: {
                    /** @example application/json */
                    "Content-Type"?: string;
                };
                path: {
                    /** @example 1 */
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "appointment_date": "2026-11-05",
                     *       "appointment_time": "2026-03-09T07:40:02.877Z",
                     *       "type": "anim consectetur",
                     *       "status": "cancelled",
                     *       "medical_record": null,
                     *       "inspection_record": null,
                     *       "staff_id": 87
                     *     }
                     */
                    "application/json": {
                        appointment_date: string;
                        appointment_time: string;
                        type: string;
                        /** @enum {string} */
                        status: "scheduled" | "completed" | "cancelled" | "request_cancel";
                        staff_id: number;
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                appointment_id: number;
                                patient: {
                                    /** @description ID */
                                    id: number;
                                    /** @description name */
                                    name: string;
                                };
                                staff: {
                                    id: number;
                                    /** @description name */
                                    name: string;
                                };
                                appointment_date: string;
                                appointment_time: string;
                                type: string;
                                /** @enum {string} */
                                status: "scheduled" | "completed" | "cancelled" | "request_cancel";
                                medical_record?: {
                                    /** @description ID */
                                    id: number;
                                    date: string;
                                    history: string;
                                    status: string;
                                    detail: {
                                        id: number;
                                        type_id: number;
                                        diagnosis: string;
                                    }[];
                                } | null;
                                inspection_record?: {
                                    /** @description ID */
                                    id: number;
                                    /** Format: date */
                                    date: string;
                                    history: string;
                                    status: string;
                                } | null;
                            };
                        };
                    };
                };
                400: components["responses"]["400 Bad Request"];
                401: components["responses"]["401 Unauthorized"];
                403: components["responses"]["403 Forbidden"];
                404: components["responses"]["404 Not Found"];
                409: components["responses"]["409 Conflict"];
                422: components["responses"]["422 Unprocessable Entity"];
                500: components["responses"]["500 Internal Server Error"];
            };
        };
        post?: never;
        /** appointments */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["401 Unauthorized"];
                403: components["responses"]["403 Forbidden"];
                404: components["responses"]["404 Not Found"];
                409: components["responses"]["409 Conflict"];
                500: components["responses"]["500 Internal Server Error"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/appointments/available-slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** available-slots */
        get: {
            parameters: {
                query?: {
                    /** @example {{$date.now}} */
                    date?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "data": {
                         *         "available-slots": [
                         *           {
                         *             "time": "09:00",
                         *             "available_dentist_ids": [
                         *               1,
                         *               2
                         *             ]
                         *           },
                         *           {
                         *             "time": "09:30",
                         *             "available_dentist_ids": [
                         *               1
                         *             ]
                         *           },
                         *           {
                         *             "time": "10:30",
                         *             "available_dentist_ids": []
                         *           }
                         *         ]
                         *       }
                         *     }
                         */
                        "application/json": {
                            data: {
                                available_slots: {
                                    /** Format: time */
                                    time: string;
                                    available_dentist_ids: (number | null)[];
                                }[];
                            };
                        };
                    };
                };
                400: components["responses"]["400 Bad Request"];
                401: components["responses"]["401 Unauthorized"];
                403: components["responses"]["403 Forbidden"];
                500: components["responses"]["500 Internal Server Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/staff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** staffs */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description List of staff members */
                            data: {
                                /** @description Unique identifier of staff */
                                id: number;
                                /** @description Full name of staff */
                                name: string;
                                /**
                                 * Format: email
                                 * @description Email address
                                 */
                                email: string;
                                /**
                                 * @description Role of staff
                                 * @enum {string}
                                 */
                                role: "dentist" | "staff";
                            }[];
                        };
                    };
                };
                400: components["responses"]["400 Bad Request"];
                401: components["responses"]["401 Unauthorized"];
                403: components["responses"]["403 Forbidden"];
                500: components["responses"]["500 Internal Server Error"];
            };
        };
        put?: never;
        /** staff */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @example application/json */
                    "Content-Type"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        first_name: string;
                        last_name: string;
                        /** Format: date */
                        birthday: string;
                        /** Format: email */
                        email: string;
                        phone: string;
                        license_number?: string | null;
                        /** @enum {string} */
                        role: "dentist" | "staff";
                    };
                };
            };
            responses: {
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description ข้อมูลที่ส่งคืน */
                            data: {
                                /** @description ID */
                                id: number;
                                /** @description name */
                                name: string;
                                /** Format: email */
                                email: string;
                            };
                        };
                    };
                };
                400: components["responses"]["400 Bad Request"];
                401: components["responses"]["401 Unauthorized"];
                403: components["responses"]["403 Forbidden"];
                409: components["responses"]["409 Conflict"];
                500: components["responses"]["500 Internal Server Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/staff/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** staff */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["staff"];
                        };
                    };
                };
                400: components["responses"]["400 Bad Request"];
                401: components["responses"]["401 Unauthorized"];
                403: components["responses"]["403 Forbidden"];
                404: components["responses"]["404 Not Found"];
                500: components["responses"]["500 Internal Server Error"];
            };
        };
        /** staff */
        put: {
            parameters: {
                query?: never;
                header?: {
                    /** @example application/json */
                    "Content-Type"?: string;
                };
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        first_name: string;
                        last_name: string;
                        /** Format: date */
                        birthday: string;
                        /** Format: email */
                        email: string;
                        phone: string;
                        license_number: string | null;
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description ข้อมูลที่ส่งคืน */
                            data: {
                                /** @description ID */
                                id: number;
                                /** @description name */
                                name: string;
                                /** Format: email */
                                email: string;
                            };
                        };
                    };
                };
                400: components["responses"]["400 Bad Request"];
                401: components["responses"]["401 Unauthorized"];
                403: components["responses"]["403 Forbidden"];
                404: components["responses"]["404 Not Found"];
                409: components["responses"]["409 Conflict"];
                500: components["responses"]["500 Internal Server Error"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/staff/dentists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * dentists
         * @description ใช้ดึงเพื่อเช็คคุณหมอที่ว่างอยู่
         */
        get: {
            parameters: {
                query: {
                    appointmentTime: string;
                    "appointmentTime ": string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description List of staff members */
                            data: {
                                /** @description Unique identifier of staff */
                                id: number;
                                /** @description Full name of staff */
                                name: string;
                                /**
                                 * Format: email
                                 * @description Email address
                                 */
                                email: string;
                            }[];
                        };
                    };
                };
                400: components["responses"]["400 Bad Request"];
                401: components["responses"]["401 Unauthorized"];
                403: components["responses"]["403 Forbidden"];
                404: components["responses"]["404 Not Found"];
                500: components["responses"]["500 Internal Server Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/work_schedules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** work_schedules */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description ข้อมูลที่ส่งคืน */
                            data: {
                                /** @description ID */
                                id: string;
                                /** @enum {string} */
                                date: "Mon" | "Tue" | "Wed" | "Thu" | "Fri" | "Sat" | "Sun";
                                /** Format: time */
                                start_time: string;
                                /** Format: time */
                                end_time: string;
                            }[];
                        };
                    };
                };
                401: components["responses"]["401 Unauthorized"];
                403: components["responses"]["403 Forbidden"];
                500: components["responses"]["500 Internal Server Error"];
            };
        };
        put?: never;
        /** work_schedule */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @example application/json */
                    "Content-Type"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "staff_id": 1,
                     *       "date": "Sat",
                     *       "start_time": "05:45",
                     *       "end_time": "16:26"
                     *     }
                     */
                    "application/json": {
                        staff_id: number;
                        /** @enum {string} */
                        date: "Mon" | "Tue" | "Wed" | "Thu" | "Fri" | "Sat" | "Sun";
                        start_time: string;
                        end_time: string;
                    };
                };
            };
            responses: {
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description ข้อมูลที่ส่งคืน */
                            data: {
                                /** @description ID */
                                id: string;
                                staff: {
                                    /** @description ID */
                                    id: string;
                                    /** @description name */
                                    name: string;
                                    role: string;
                                };
                                /** @enum {string} */
                                date: "Mon" | "Tue" | "Wed" | "Thu" | "Fri" | "Sat" | "Sun";
                                /** Format: time */
                                start_time: string;
                                /** Format: time */
                                end_time: string;
                                is_active: boolean;
                            };
                        };
                    };
                };
                400: components["responses"]["400 Bad Request"];
                401: components["responses"]["401 Unauthorized"];
                403: components["responses"]["403 Forbidden"];
                409: components["responses"]["409 Conflict"];
                500: components["responses"]["500 Internal Server Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/work_schedules/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** work_schedule */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["work_schedules"];
                        };
                    };
                };
                401: components["responses"]["401 Unauthorized"];
                403: components["responses"]["403 Forbidden"];
                404: components["responses"]["404 Not Found"];
                500: components["responses"]["500 Internal Server Error"];
            };
        };
        /** work_schedule */
        put: {
            parameters: {
                query?: never;
                header?: {
                    /** @example application/json */
                    "Content-Type"?: string;
                };
                path: {
                    /** @example 21 */
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "date": "Sat",
                     *       "start_time": "18:30",
                     *       "end_time": "21:41",
                     *       "is_active": false
                     *     }
                     */
                    "application/json": {
                        /** @enum {string} */
                        date: "Mon" | "Tue" | "Wed" | "Thu" | "Fri" | "Sat" | "Sun";
                        /** Format: time */
                        start_time: string;
                        /** Format: time */
                        end_time: string;
                        is_active: boolean;
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                /** @description ID */
                                id: string;
                                staff: {
                                    /** @description ID */
                                    id: string;
                                    /** @description name */
                                    name: string;
                                    role: string;
                                };
                                /** @enum {string} */
                                date: "Mon" | "Tue" | "Wed" | "Thu" | "Fri" | "Sat" | "Sun";
                                /** Format: time */
                                start_time: string;
                                /** Format: time */
                                end_time: string;
                                is_active: boolean;
                            };
                        };
                    };
                };
                400: components["responses"]["400 Bad Request"];
                401: components["responses"]["401 Unauthorized"];
                403: components["responses"]["403 Forbidden"];
                404: components["responses"]["404 Not Found"];
                409: components["responses"]["409 Conflict"];
                422: components["responses"]["422 Unprocessable Entity"];
                500: components["responses"]["500 Internal Server Error"];
            };
        };
        post?: never;
        /** work_schedule */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["400 Bad Request"];
                401: components["responses"]["401 Unauthorized"];
                403: components["responses"]["403 Forbidden"];
                404: components["responses"]["404 Not Found"];
                409: components["responses"]["409 Conflict"];
                500: components["responses"]["500 Internal Server Error"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/patients/{patient_id}/medical_records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * medical_records
         * @description ประวัติการรักษาโดยรวมทั้งหมด ของคนไข้ 1 คน
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    patient_id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                /** @description ID */
                                id: number;
                                date: string;
                                history: string;
                                status: string;
                                patient_id: number;
                                inspection_record_id: number;
                            }[];
                        };
                    };
                };
                400: components["responses"]["400 Bad Request"];
                401: components["responses"]["401 Unauthorized"];
                403: components["responses"]["403 Forbidden"];
                500: components["responses"]["500 Internal Server Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/medical_records/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * medical_record
         * @description ดึงข้อมูล บันทึกการตรวจ โดยหมอดูได้ทั้งหมด คนไข้ต้องเช็คดูว่าประวัติของตนไหม
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                /** @description ID */
                                id: number;
                                patients_id: number;
                                /** Format: date */
                                date: string;
                                history: string;
                                /** @description status */
                                status: string;
                                detail: {
                                    id: number;
                                    examination_type: {
                                        id: number;
                                        name: string;
                                    };
                                    diagnosis: string;
                                }[];
                                inspection_record: {
                                    id: number;
                                    /** Format: date */
                                    date: string;
                                    history: string;
                                    status: string;
                                };
                            };
                        };
                    };
                };
                400: components["responses"]["400 Bad Request"];
                401: components["responses"]["401 Unauthorized"];
                403: components["responses"]["403 Forbidden"];
                404: components["responses"]["404 Not Found"];
                500: components["responses"]["500 Internal Server Error"];
            };
        };
        /** medical_records */
        put: {
            parameters: {
                query?: never;
                header?: {
                    /** @example application/json */
                    "Content-Type"?: string;
                };
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description ID */
                        id: number;
                        date: string;
                        history: string;
                        status: string;
                        detail: {
                            id: number;
                            type_id: number;
                            diagnosis: string;
                        }[];
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                /** @description ID */
                                id: number;
                                patients_id: number;
                                /** Format: date */
                                date: string;
                                history: string;
                                /** @description status */
                                status: string;
                                detail: {
                                    id: number;
                                    examination_type: {
                                        /** @description ID */
                                        id: number;
                                        name: string;
                                    };
                                    diagnosis: string;
                                }[];
                                inspection_record: {
                                    id: number;
                                    /** Format: date */
                                    date: string;
                                    history: string;
                                    status: string;
                                };
                            };
                        };
                    };
                };
                400: components["responses"]["400 Bad Request"];
                401: components["responses"]["401 Unauthorized"];
                403: components["responses"]["403 Forbidden"];
                404: components["responses"]["404 Not Found"];
                409: components["responses"]["409 Conflict"];
                422: components["responses"]["422 Unprocessable Entity"];
                500: components["responses"]["500 Internal Server Error"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/medical_records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** medical_records */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @example application/json */
                    "Content-Type"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        date: string;
                        history: string;
                        status: string;
                        patient_id: number;
                        detail: {
                            type_id: number;
                            diagnosis: string;
                        }[];
                        inspection_record_id: number;
                    };
                };
            };
            responses: {
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                /** @description ID */
                                id: number;
                                patients_id: number;
                                /** Format: date */
                                date: string;
                                history: string;
                                /** @description status */
                                status: string;
                                detail: {
                                    id: number;
                                    examination_type: {
                                        id: number;
                                        name: string;
                                    };
                                    diagnosis: string;
                                }[];
                                inspection_record: {
                                    id: number;
                                    /** Format: date */
                                    date: string;
                                    history: string;
                                    status: string;
                                };
                            };
                        };
                    };
                };
                400: components["responses"]["400 Bad Request"];
                401: components["responses"]["401 Unauthorized"];
                403: components["responses"]["403 Forbidden"];
                409: components["responses"]["409 Conflict"];
                422: components["responses"]["422 Unprocessable Entity"];
                500: components["responses"]["500 Internal Server Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** types */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                /** @description ID */
                                id: number;
                                name: string;
                            }[];
                        };
                    };
                };
                400: components["responses"]["400 Bad Request"];
                401: components["responses"]["401 Unauthorized"];
                403: components["responses"]["403 Forbidden"];
                500: components["responses"]["500 Internal Server Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inspection_records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** inspection_records */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                id: number;
                                patient_id: string;
                                /** Format: date */
                                date: string;
                                history: string;
                                /** @description status */
                                status: string;
                            }[];
                        };
                    };
                };
                401: components["responses"]["401 Unauthorized"];
                403: components["responses"]["403 Forbidden"];
                500: components["responses"]["500 Internal Server Error"];
            };
        };
        put?: never;
        /** inspection_records */
        post: {
            parameters: {
                query?: never;
                header?: {
                    /** @example application/json */
                    "Content-Type"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: date */
                        date: string;
                        history: string;
                        status: string;
                        patient_id: number;
                    };
                };
            };
            responses: {
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                /** @description ID */
                                id: number;
                                /** Format: date */
                                date: string;
                                history: string;
                                status: string;
                            };
                        };
                    };
                };
                400: components["responses"]["400 Bad Request"];
                401: components["responses"]["401 Unauthorized"];
                403: components["responses"]["403 Forbidden"];
                409: components["responses"]["409 Conflict"];
                422: components["responses"]["422 Unprocessable Entity"];
                500: components["responses"]["500 Internal Server Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inspection_records/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** inspection_record */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["inspection_record"];
                        };
                    };
                };
                401: components["responses"]["401 Unauthorized"];
                403: components["responses"]["403 Forbidden"];
                404: components["responses"]["404 Not Found"];
                500: components["responses"]["500 Internal Server Error"];
            };
        };
        /** inspection_records */
        put: {
            parameters: {
                query?: never;
                header?: {
                    /** @example application/json */
                    "Content-Type"?: string;
                };
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description status */
                        status: string | null;
                        history: string | null;
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                /** @description ID */
                                id: number;
                                /** Format: date */
                                date: string;
                                history: string;
                                status: string;
                                patient_id: number;
                            };
                        };
                    };
                };
                400: components["responses"]["400 Bad Request"];
                401: components["responses"]["401 Unauthorized"];
                403: components["responses"]["403 Forbidden"];
                404: components["responses"]["404 Not Found"];
                409: components["responses"]["409 Conflict"];
                422: components["responses"]["422 Unprocessable Entity"];
                500: components["responses"]["500 Internal Server Error"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/company/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** company */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: {
                                contect_name: string;
                                office_name: string;
                                phone: string;
                                address: string;
                                email: string;
                            };
                        };
                    };
                };
                401: components["responses"]["401 Unauthorized"];
                403: components["responses"]["403 Forbidden"];
                404: components["responses"]["404 Not Found"];
                500: components["responses"]["500 Internal Server Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mobile_dentals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** mobile_dentals */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                mobile_dental_id: number;
                                company_id: number;
                                /** Format: date */
                                date: string;
                                count: number;
                                /** @enum {string} */
                                status: "request" | "scheduled" | "completed" | "request_cancel" | "cancel";
                                address: string;
                            }[];
                        };
                    };
                };
                401: components["responses"]["401 Unauthorized"];
                403: components["responses"]["403 Forbidden"];
                500: components["responses"]["500 Internal Server Error"];
            };
        };
        put?: never;
        /** mobile_dentals */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        date: string;
                        /** @description จำนวนคน */
                        count: number;
                        /** @description สถานที่ */
                        address: string;
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                mobile_dental_id: number;
                                company_id: number;
                                /** Format: date */
                                date: string;
                                count: number;
                                /** @enum {string} */
                                status: "request" | "scheduled" | "completed" | "request_cancel" | "cancel";
                                address: string;
                            };
                        };
                    };
                };
                400: components["responses"]["400 Bad Request"];
                401: components["responses"]["401 Unauthorized"];
                403: components["responses"]["403 Forbidden"];
                409: components["responses"]["409 Conflict"];
                422: components["responses"]["422 Unprocessable Entity"];
                500: components["responses"]["500 Internal Server Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mobile_dentals/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** mobile_dental */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["mobile_dental"];
                        };
                    };
                };
                401: components["responses"]["401 Unauthorized"];
                403: components["responses"]["403 Forbidden"];
                404: components["responses"]["404 Not Found"];
                500: components["responses"]["500 Internal Server Error"];
            };
        };
        /** mobile_dentals */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "request" | "scheduled" | "completed" | "request_cancel" | "cancel";
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                mobile_dental_id: number;
                                company_id: number;
                                /** Format: date */
                                date: string;
                                count: number;
                                status: string;
                                address: string;
                            };
                        };
                    };
                };
                400: components["responses"]["400 Bad Request"];
                401: components["responses"]["401 Unauthorized"];
                403: components["responses"]["403 Forbidden"];
                404: components["responses"]["404 Not Found"];
                409: components["responses"]["409 Conflict"];
                422: components["responses"]["422 Unprocessable Entity"];
                500: components["responses"]["500 Internal Server Error"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mobile-dental/{mobile_dental_id}/patients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** patient_in_mobile */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    mobile_dental_id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        first_name: string;
                        last_name: string;
                        birthday: string;
                        phone: string;
                        idcard: string;
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                patient_id: number;
                                name: string;
                                status: string;
                            }[];
                        };
                    };
                };
                400: components["responses"]["400 Bad Request"];
                401: components["responses"]["401 Unauthorized"];
                403: components["responses"]["403 Forbidden"];
                409: components["responses"]["409 Conflict"];
                500: components["responses"]["500 Internal Server Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        patient: {
            id: number;
            name: string;
            /** Format: email */
            email: string;
            phone: string;
            /** Format: date */
            birthday: string;
            allergy?: string | null;
        };
        appointment: {
            appointment_id: number;
            patient: {
                /** @description ID */
                id: number;
                /** @description name */
                name: string;
            };
            staff: {
                id: number;
                /** @description name */
                name: string;
            };
            appointment_date: string;
            appointment_time: string;
            type: string;
            /** @enum {string} */
            status: "scheduled" | "completed" | "cancelled" | "request_cancel";
            medical_record?: {
                /** @description ID */
                id: number;
                date: string;
                history: string;
                status: string;
                detail: {
                    id: number;
                    type_id: number;
                    diagnosis: string;
                }[];
            } | null;
            inspection_record?: {
                /** @description ID */
                id: number;
                /** Format: date */
                date: string;
                history: string;
                status: string;
            } | null;
        };
        staff: {
            /** @description Unique identifier of staff */
            id: number;
            /**
             * @description Full name of staff
             * @example Dr. John Doe
             */
            name: string;
            /**
             * Format: email
             * @description Email address
             * @example john.doe@example.com
             */
            email: string;
            /** @description Phone number */
            phone?: string;
            /**
             * Format: date
             * @description Date of birth (YYYY-MM-DD)
             * @example 1990-05-20
             */
            birthday: string;
            /**
             * @description Professional license number (nullable for non-dentist staff)
             * @example DEN-123456
             */
            license_number?: string | null;
            /**
             * @description Role of staff in system
             * @enum {string}
             */
            role: "dentist" | "staff";
        };
        /** @description ข้อมูลที่ส่งคืน */
        work_schedules: {
            /** @description ID */
            id: string;
            staff: {
                /** @description ID */
                id: string;
                /** @description name */
                name: string;
                role: string;
            };
            /** @enum {string} */
            date: "Mon" | "Tue" | "Wed" | "Thu" | "Fri" | "Sat" | "Sun";
            /** Format: time */
            start_time: string;
            /** Format: time */
            end_time: string;
            is_active: boolean;
        };
        medical_record: {
            /** @description ID */
            id: number;
            date: string;
            history: string;
            status: string;
            patient_id: number;
            detail: {
                id: number;
                type_id: number;
                diagnosis: string;
            }[];
            inspection_record_id: number;
        };
        inspection_record: {
            /** @description ID */
            id: number;
            /** Format: date */
            date: string;
            history: string;
            status: string;
            patient_id: number;
        };
        mobile_dental: {
            mobile_dental_id: number;
            company_id: number;
            /** Format: date */
            date: string;
            count: number;
            /** @enum {string} */
            status: "request" | "scheduled" | "completed" | "request_cancel" | "cancel";
            address: string;
        };
    };
    responses: {
        "400 Bad Request": {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    error: {
                        /** @default AUTH-001 */
                        code: string;
                        /** @default Authentication required */
                        message: string;
                        /** @default AUTHENTICATION */
                        category: string | null;
                        traceId: string;
                    };
                };
            };
        };
        "404 Not Found": {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    error: {
                        /** @default USER-001 */
                        code: string;
                        /** @default User not found */
                        message: string;
                        /** @default RESOURCE */
                        category: string | null;
                        traceId: string;
                    };
                };
            };
        };
        "401 Unauthorized": {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    error: {
                        /** @default VAL-001 */
                        code: string;
                        /** @default validation fail */
                        message: string;
                        details?: ({
                            field: string;
                            code: string;
                            message: string | null;
                        } | null)[] | null;
                        /** @default VALIDATION */
                        category: string | null;
                        traceId: string;
                    };
                };
            };
        };
        "403 Forbidden": {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    error: {
                        /** @default AUTH-003 */
                        code: string;
                        /** @default Access denied */
                        message: string;
                        /** @default AUTHORIZATION */
                        category: string | null;
                        traceId: string;
                    };
                };
            };
        };
        "409 Conflict": {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    error: {
                        /** @default USER-002 */
                        code: string;
                        /** @default Email already exists */
                        message: string;
                        /** @default BUSINESS */
                        category: string | null;
                        traceId: string;
                    };
                };
            };
        };
        "422 Unprocessable Entity": {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    error: {
                        /** @default ORDER-004 */
                        code: string;
                        /** @default Insufficient balance */
                        message: string;
                        /** @default BUSINESS */
                        category: string | null;
                        traceId: string;
                    };
                };
            };
        };
        "500 Internal Server Error": {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    error: {
                        /** @default SYS-001 */
                        code: string;
                        /** @default Internal server error */
                        message: string;
                        /** @default SYSTEM */
                        category: string | null;
                        traceId: string;
                    };
                };
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
